// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZqvXTGTKzQQYnvPSxwO2nuOq0k__Q5ME',
    appId: '1:695074261735:web:9e9d00a0550f77a26fb042',
    messagingSenderId: '695074261735',
    projectId: 'chatapptute-35be2',
    authDomain: 'chatapptute-35be2.firebaseapp.com',
    storageBucket: 'chatapptute-35be2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2KilTB0tcoBZpvlQi4_kZKGnzqeSYPK8',
    appId: '1:695074261735:android:a8d8a8e2f96e8bd26fb042',
    messagingSenderId: '695074261735',
    projectId: 'chatapptute-35be2',
    storageBucket: 'chatapptute-35be2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZqvXTGTKzQQYnvPSxwO2nuOq0k__Q5ME',
    appId: '1:695074261735:web:f3e6e7f767ccdd636fb042',
    messagingSenderId: '695074261735',
    projectId: 'chatapptute-35be2',
    authDomain: 'chatapptute-35be2.firebaseapp.com',
    storageBucket: 'chatapptute-35be2.firebasestorage.app',
  );
}
